modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/MimicWorld/issues"
license="MIT"

[[mods]]
modId="mimicworld"
version="${file.jarVersion}"
displayName="Mimic World"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mimicworld"
authors="ShyNieke, Mrbysco"
description='''
Adds a dimension that is a copy of the vanilla overworld
'''
[[dependencies.mimicworld]]
modId="minecraft"
type="required"
versionRange="[1.21.11,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.mimicworld]]
modId="neoforge"
type="required"
versionRange="[21.11.0-beta,)"
ordering="NONE"
side="BOTH"